rootProject.name = "engine"

include("core")
include("core-processor")
include("graphics:api")
include("graphics:common")
include("graphics:opengl")
include("graphics:vulcan")
include("graphics:webgpu")
include("providers:lwjgl-glfw")
include("providers:sdl3")
include("providers:assimp")
include("providers:slang")
include("providers:lwjgl-gl")
include("providers:lwjgl-vk")
include("providers:jwebgpu")
include("providers:teavm-webgpu")
include("providers:teavm-windowing")
include("examples")
include("web")
