rootProject.name = "engine"

include("core")
include("graphics:api")
include("graphics:common")
include("graphics:opengl")
include("graphics:vulcan")
include("graphics:webgpu")
include("windowing:glfw")
include("bindings:sdl3")
include("bindings:wgpu")
include("bindings:assimp")
include("bindings:slang")
include("providers:lwjgl-gl")
include("providers:jwebgpu")
include("examples")
