package dev.engine.core.input;

public enum KeyCode implements BooleanSource {
    A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z,
    NUM_0, NUM_1, NUM_2, NUM_3, NUM_4, NUM_5, NUM_6, NUM_7, NUM_8, NUM_9,
    NUMPAD_0, NUMPAD_1, NUMPAD_2, NUMPAD_3, NUMPAD_4, NUMPAD_5,
    NUMPAD_6, NUMPAD_7, NUMPAD_8, NUMPAD_9,
    NUMPAD_ADD, NUMPAD_SUBTRACT, NUMPAD_MULTIPLY, NUMPAD_DIVIDE,
    NUMPAD_ENTER, NUMPAD_DECIMAL,
    F1, F2, F3, F4, F5, F6, F7, F8, F9, F10, F11, F12,
    SPACE, ENTER, ESCAPE, TAB, BACKSPACE, DELETE, INSERT,
    HOME, END, PAGE_UP, PAGE_DOWN,
    LEFT, RIGHT, UP, DOWN,
    LEFT_SHIFT, RIGHT_SHIFT, LEFT_CTRL, RIGHT_CTRL,
    LEFT_ALT, RIGHT_ALT, LEFT_SUPER, RIGHT_SUPER,
    CAPS_LOCK, NUM_LOCK, SCROLL_LOCK, PRINT_SCREEN, PAUSE,
    COMMA, PERIOD, SLASH, SEMICOLON, APOSTROPHE,
    LEFT_BRACKET, RIGHT_BRACKET, BACKSLASH, GRAVE_ACCENT,
    MINUS, EQUALS, MENU,
    UNKNOWN
}
